env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'prettier'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - prettier
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
